namespace Unity.XR.PXR
{
    public enum ControllerKeyEnum
    {
        CONTROLLER_KEY_JOYSTICK=0,
        CONTROLLER_KEY_MENU=1,
        CONTROLLER_KEY_TRIGGER=2,
        CONTROLLER_KEY_RIGHT_A=3,
        CONTROLLER_KEY_RIGHT_B=4,
        CONTROLLER_KEY_LEFT_X=5,
        CONTROLLER_KEY_LEFT_Y=6,
        CONTROLLER_KEY_LEFT_GRIP=7,
        CONTROLLER_KEY_RIGHT_GRIP=8,
        CONTROLLER_KEY_VOLUME_DOWN=9,
        CONTROLLER_KEY_VOLUME_UP=10,
        CONTROLLER_KEY_CLICK=11
    }
}