namespace Unity.XR.PXR
{
    public enum CustomizeSettingsTabEnum
    {
        CUSTOMIZE_SETTINGS_TAB_WLAN = 0,
        CUSTOMIZE_SETTINGS_TAB_CONTROLLER = 1,
        CUSTOMIZE_SETTINGS_TAB_BLUETOOTH = 2,
        CUSTOMIZE_SETTINGS_TAB_DISPLAY = 3,
        CUSTOMIZE_SETTINGS_TAB_LAB = 4,
        CUSTOMIZE_SETTINGS_TAB_GENERAL_LOCKSCREEN = 5,
        CUSTOMIZE_SETTINGS_TAB_GENERAL_FACTORY_RESET = 6
    }
}