namespace Unity.XR.PXR
{
    public enum PICOCastOptionValueEnum
    {
        OPTION_VALUE_RESOLUTION_HIGH,
        OPTION_VALUE_RESOLUTION_MIDDL,
        OPTION_VALUE_RESOLUTION_AUTO,
        OPTION_VALUE_RESOLUTION_HIGH_2K,
        OPTION_VALUE_RESOLUTION_HIGH_4K,

        OPTION_VALUE_BITRATE_HIGH,
        OPTION_VALUE_BITRATE_MIDDLE,
        OPTION_VALUE_BITRATE_LOW,

        OPTION_VALUE_AUDIO_ON,
        OPTION_VALUE_AUDIO_OFF,

        STATUS_VALUE_STATE_STARTED,
        STATUS_VALUE_STATE_STOPPED,
        STATUS_VALUE_ERROR
    }
}