namespace Unity.XR.PXR
{
    public enum StartVRSettingsEnum
    {
        START_VR_SETTINGS_ITEM_WIFI=0,
        START_VR_SETTINGS_ITEM_BLUETOOT=1,
        START_VR_SETTINGS_ITEM_CONTROLLER=2,
        START_VR_SETTINGS_ITEM_LAB=3,
        START_VR_SETTINGS_ITEM_BRIGHTNESS=4,
        START_VR_SETTINGS_ITEM_GENERAL=5,
        START_VR_SETTINGS_ITEM_NOTIFICATION=6
    }
}