namespace Unity.XR.PXR
{
    public enum SystemInfoEnum
    {
        ELECTRIC_QUANTITY=0,
        PUI_VERSION=1,
        EQUIPMENT_MODEL=2,
        EQUIPMENT_SN=3,
        CUSTOMER_SN=4,
        INTERNAL_STORAGE_SPACE_OF_THE_DEVICE=5,
        DEVICE_BLUETOOTH_STATUS=6,
        BLUETOOTH_NAME_CONNECTED=7,
        BLUETOOTH_MAC_ADDRESS=8,
        DEVICE_WIFI_STATUS=9,
        WIFI_NAME_CONNECTED=10,
        WLAN_MAC_ADDRESS=11,
        DEVICE_IP=12,
        CHARGING_STATUS=13
    }
}